const express = require("express")
const app = express()
const cors = require("cors")
const Words = require("./routes/words.routes")
const WordsPost = require("./routes/words.routes")
const wordsUpdate = require("./routes/words.routes")
const wordsDelete = require("./routes/words.routes")
const getUsers = require("./routes/user.routes")
const createUser = require("./routes/user.routes")
const deleteUser = require("./routes/user.routes")
const getResults = require("./routes/result.routes")
const createResults = require("./routes/result.routes")
const deleteResult = require("./routes/result.routes")

app.use(express.json())
app.use(cors())

app.use("/api",Words)
app.use("/api",WordsPost)
app.use("/api",wordsUpdate)
app.use("/api",wordsDelete)
app.use("/api",getUsers)
app.use("/api",createUser)
app.use("/api",deleteUser)
app.use("/api",getResults)
app.use("/api",createResults)
app.use("/api",deleteResult)

module.exports = app